/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LazyLoad {
        "altText": string;
        "imgSrc": string;
    }
    interface LazySpinner {
    }
}
declare global {
    interface HTMLLazyLoadElement extends Components.LazyLoad, HTMLStencilElement {
    }
    var HTMLLazyLoadElement: {
        prototype: HTMLLazyLoadElement;
        new (): HTMLLazyLoadElement;
    };
    interface HTMLLazySpinnerElement extends Components.LazySpinner, HTMLStencilElement {
    }
    var HTMLLazySpinnerElement: {
        prototype: HTMLLazySpinnerElement;
        new (): HTMLLazySpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "lazy-load": HTMLLazyLoadElement;
        "lazy-spinner": HTMLLazySpinnerElement;
    }
}
declare namespace LocalJSX {
    interface LazyLoad {
        "altText"?: string;
        "imgSrc"?: string;
    }
    interface LazySpinner {
    }
    interface IntrinsicElements {
        "lazy-load": LazyLoad;
        "lazy-spinner": LazySpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lazy-load": LocalJSX.LazyLoad & JSXBase.HTMLAttributes<HTMLLazyLoadElement>;
            "lazy-spinner": LocalJSX.LazySpinner & JSXBase.HTMLAttributes<HTMLLazySpinnerElement>;
        }
    }
}
